### ISSUE TITLE
Category List -- Search

### ISSUE THREAD

**Issue by faithtek** [Kademi/kademi-dev#5035] opened 2018-02-25 19:37 UTC
http://asrdev.admin.kademi.us/reward-store/general-1/#products-tab

Category Searching here doesn't work. 

When a Category is searched (say "home"):
- Selected categories goto the bottom of the list not the top. This is also true no matter whether you search or not.
- There is no way to clear the search item and return to the standard category list without refreshing the page

The category list on this page: http://asrdev.admin.kademi.us/reward-store/general-1/?addProducts works like it should.

**Comment by gonzalon** [comment] 2018-02-26 03:40
@faithtek If you found yourself in this situation:

Search "Fishing":
![image](https://user-images.githubusercontent.com/2773216/36652399-7b8dc820-1b13-11e8-8d13-9596a0a7540e.png)

Un select "Fishing"
![image](https://user-images.githubusercontent.com/2773216/36652412-8faeef64-1b13-11e8-9a11-bbb95d2b3311.png)

If you press the backspace at this stage it would show you the original list:
![image](https://user-images.githubusercontent.com/2773216/36652474-c8ad2132-1b13-11e8-962e-240c284c9d6e.png)

**Comment by faithtek** [comment] 2018-02-26 04:09
Yes. That is the way it should work. Sadly on http://asrdev.admin.kademi.us/reward-store/general-1/#products-tab It does the following.

- When you search:
![image6](https://user-images.githubusercontent.com/7914822/36653042-a85030de-1a80-11e8-92bc-455058f632e2.png)

- When you clear the category:
![image5](https://user-images.githubusercontent.com/7914822/36653064-db698240-1a80-11e8-8823-d05e30a5e4bb.png)

**Comment by bradmac** [comment] 2018-02-26 04:56
We've just deployed to the US cluster. @gonzalon please check that now works as intended

**Comment by gonzalon** [comment] 2018-02-26 04:59
@faithtek Hi Michael, I just tested this its fixed in the US cluster at the moment. I made my comment before the deploy. 
Anyways I just assigned this issue to one of our testers so he can confirm that everything works as expected. Thanks!

**Comment by Uafinder** [comment] 2018-03-03 10:16
Heya, looks bad for me
![image](https://user-images.githubusercontent.com/1945230/36933112-7ae46ace-1edc-11e8-8cc2-3d286b2b4a8d.png)
http://asrdev.admin.kademi.us/reward-store/general-1/?q=&categoryName=

Search result appears in bottom

**Comment by bradmac** [comment] 2018-03-05 23:07
Category filter needs the same update that was done here:
https://github.com/Kademi/kademi-dev/issues/4916

**Comment by bradmac** [comment] 2018-03-06 00:18
Done for reward store screens, add and remove modes

![image](https://user-images.githubusercontent.com/826458/37007148-cfc38e10-2140-11e8-8e56-580d62d06f3c.png)

**Comment by Uafinder** [comment] 2018-03-06 11:27
I'm still seeing this on prod site
![image](https://user-images.githubusercontent.com/1945230/37029780-4099c3d4-2141-11e8-9d92-65510a3034e5.png)
http://asrdev.admin.kademi.us/reward-store/general-1/?q=&categoryName=

Am i missing something?

**Comment by bradmac** [comment] 2018-03-06 20:35
@Uafinder we havent deployed to production yet.  Its just ready for test in CI

**Comment by Uafinder** [comment] 2018-03-20 16:12
Yeah, looks great at the moment

**Closed by Uafinder** 2018-03-20 16:12 UTC
Labels: High priority, Ready to Test - Dev, bug
