### ISSUE TITLE
KCom2 - Product image uploader does not upload / associate more than one image at a time

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6036] opened 2018-09-27 21:26 UTC
Here's my testing procedure:

Visit: https://waterware.admin.kademi.com.au/products/ and notice product "HPVMPS" has no images.
Visit https://waterware.admin.kademi.com.au/product-images/ and upload the following files.

![hpvmps](https://user-images.githubusercontent.com/39784677/46175369-d7563400-c2ff-11e8-99bc-4c7bea5e3623.jpg)

As per instructions, rename one of these images as **HPVMPS.jpg** and duplicate another and name as **HPVMPS.2.jpg**.

Visit the product again and you'll see that only one image was uploaded - not two.

Waterware needs to update 1700 products which all have at least 2, but mainly 4-5 images, per product.

**Comment by bradmac** [comment] 2018-09-27 21:34
OK, so the issue is that the upload process needs to allow for updating existing images.

The current process works when the suffix identifies a product option, because that gives us a specific item to update. But the matching logic isnt correct when using incremental identifiers, which means new images just overwrite the first.

**Comment by stephen-fueldesign** [comment] 2018-09-27 21:46
I believe you're correct Brad.
Seems to override instead of append. I tested with these image:

![hpvmps 2](https://user-images.githubusercontent.com/39784677/46176378-57ca6400-c303-11e8-84f0-52b6c41e8419.jpg)
![hpvmps](https://user-images.githubusercontent.com/39784677/46176379-5862fa80-c303-11e8-95d0-26210a90435e.jpg)

**Comment by bradmac** [comment] 2018-09-28 03:36
i think this is fixed now

**Closed by bradmac** 2018-09-28 03:36 UTC
