### ISSUE TITLE
Create Fork Journey Action Node and Enable multiple Secondary Goals for a lead

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#4680] opened 2017-12-25 09:12 UTC
We need to have a new node type called Rule Trigger, this node is a special type of goal nodes, it has no prior nodes, it contains an optional MVEL expression to evaluate, and it can be linked to a goal followed by an action.

The new node which is an action/goal node listen to various types of events, and passes it along to its next node if no MVEL expression is present, if the MVEL is present then it is checked to be true first before propagating the event to the next nodes.

If the next node was a goal node then if the event satisfies the next goal node, the goal node will transition to the next node which would be an action node, otherwise the execution will stop.

An example would be a user has a survey to finish, but the journey proceeds.. if the survey is finished within 3 days of its creation, the journey proceeds, otherwise.. the journey doesn't.

**Comment by mkhoudary** [comment] 2017-12-25 09:15
@bradmac as you remember we needed this for Vaya to support giving points after variable periods of time without blocking the journey, and also this is needed to send an email 1 day after completing a survey without blocking the journey..

After writing this down based upon our older conversation, I find the multiple current goals to the same lead is quite better for many cases including Vaya cases.. although this is a good feature.. what do you think?

**Comment by mkhoudary** [comment] 2017-12-25 09:15
https://github.com/Kademi/kademi-dev/issues/4680

**Comment by mkhoudary** [comment] 2017-12-25 09:15
https://github.com/Kademi/client-vaya/issues/231

**Comment by mkhoudary** [comment] 2017-12-25 09:17
https://github.com/Kademi/client-vaya/issues/232

**Comment by bradmac** [comment] 2017-12-26 20:38
hey @mkhoudary, yeah thinking about this more, i think we should be able to handle this with existing capabilities.

it would just be additional begin nodes (or 1 begin node with the branch goal), which might then take a single action and then end the journey

**Comment by mkhoudary** [comment] 2017-12-28 09:27
We agreed to make multiple goal feature for lead..

**Comment by mkhoudary** [comment] 2017-12-31 13:05
Done.. 

![image](https://user-images.githubusercontent.com/3704174/34461766-15b4f28e-ee3c-11e7-9362-885918c36fb2.png)

**Comment by mkhoudary** [comment] 2017-12-31 13:09
@Uafinder to test this you need to create a journey that contains a Fork node.. which will spawn several secondary paths and a primary path.. forked paths shall be executed in parallel with the default/primary path.

Example:
Fork and two secondary paths with a timer then an email to be sent and the primary with another timer or a task

**Comment by Uafinder** [comment] 2018-01-02 09:51
1. The default and secondary nodes are starting from the one point.
![image](https://user-images.githubusercontent.com/1945230/34480117-3813d084-efb3-11e7-8ac8-b67a40155e66.png)
http://vladtest16.admin.kademi-ci.co/funnels/first-journey/version1/#journeyBuilder-tab

**Comment by mkhoudary** [comment] 2018-01-02 10:42
@Uafinder this is a visual bug.. I will fix it.. but the behavior should be correct..

**Comment by Uafinder** [comment] 2018-01-02 11:26
Can't create a lead with journey setup
![image](https://user-images.githubusercontent.com/1945230/34482370-3ff0d79a-efc0-11e7-8908-ea2ff3a76a60.png)
Caused by: org.postgresql.util.PSQLException: ERROR: column "fork_id" of relation "lead_journey_transition" does not exist
http://vladtest16.admin.kademi-ci.co/manageUsers/3812989/#funnelsTab-tab

**Comment by bradmac** [comment] 2018-01-02 19:54
hey @mkhoudary just one thing, forkId should be a nullable field, but you've made it long.

Thats a primitive so cant be null, so hibernate cant automatically create the column. Thats why it hasnt been added to the CI environment

We can add that column easily, but please remember that new fields always need to be nullable, which means Long rather then long

**Comment by bradmac** [comment] 2018-01-02 20:45
Thats working now

**Comment by Uafinder** [comment] 2018-01-03 11:04
Logics work ok. Closing this issue and will open a separate ones.
https://github.com/Kademi/kademi-dev/issues/4718
https://github.com/Kademi/kademi-dev/issues/4719

**Closed by Uafinder** 2018-01-03 11:04 UTC
Labels: bug, enhancement, Ready to Test - Dev
