### ISSUE TITLE
Dashboard 'Close deal'  button missing correct dialogue

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1953] opened 2016-06-07 12:42 UTC
http://kcrm.olhub.com/dashboard

![image](https://cloud.githubusercontent.com/assets/2201340/15857854/e5017fd4-2d00-11e6-9a47-f48207a12886.png)

When clicking on the close deal button it should open the close deal dialogue.

![image](https://cloud.githubusercontent.com/assets/2201340/15857885/0bf9cdb2-2d01-11e6-8de8-ea77261cf23c.png)

**Comment by bradmac** [comment] 2016-06-07 21:49
Duplicate of https://github.com/Kademi/kademi-dev/issues/1881

**Closed by bradmac** 2016-06-07 21:49 UTC
Labels: Project KCRM
