### ISSUE TITLE
Admin dashboard reward points gadget error

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5513] opened 2018-06-03 06:39 UTC
When I open an admin dashboard with a reward points gadget, a JS error appears.

Please check Dixie's dashboard:
http://dixie.admin.kademi.us

**Comment by mkhoudary** [comment] 2018-06-03 06:40
https://github.com/Kademi/client-hinda-dixie/issues/66

**Comment by bradmac** [comment] 2018-06-26 23:18
Closing as duplicate of this
https://github.com/Kademi/kademi-dev/issues/5528

**Closed by bradmac** 2018-06-26 23:18 UTC
Labels: bug
