### ISSUE TITLE
Users manage page - filter by reward store is not working

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4180] opened 2017-10-16 10:28 UTC
![image](https://user-images.githubusercontent.com/1945230/31607595-9e376144-b275-11e7-9508-c323c14ca7db.png)
http://vlad-test17.admin.kademi-ci.co/manageUsers/
http://vlad-test18.admin.kademi-ci.co/manageUsers/

**Comment by bradmac** [comment] 2017-10-16 23:19
Duplicate of https://github.com/Kademi/kademi-dev/issues/3097

**Closed by bradmac** 2017-10-16 23:19 UTC
Labels: bug
