### ISSUE TITLE
Email group item: Should not include www when validating email domain against website domain

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#3257] opened 2017-05-22 06:06 UTC
in 3M, we do have email domain: info@racetowinrewards.com and website domain: www.racetowinrewards.com

so it doesnt allow user to save  edm settings.

**Comment by bradmac** [comment] 2017-05-22 08:29
Duplicate of https://github.com/Kademi/kademi-dev/issues/3162

**Closed by bradmac** 2017-05-22 08:29 UTC
