### ISSUE TITLE
Password reset, lookup by user identifiers

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2723] opened 2016-12-15 20:39 UTC
Update the password reset process so that the initial step will locate a profile by either:
- email (as presently)
- username
- any custom user identifier (ie from extra fields)
- phone number

The reset email is still sent to the email address, if there is one. If there is no email address the json response needs to indicate that, and the front end should display an appropriate message

**Comment by hoanglinhlan** [comment] 2017-01-09 05:34
Reset pass: 

- email: pass
- phone: pass
- any custom user identifier (ie from extra fields): failed
- username: failed

**Comment by tuzzmaniandevil** [comment] 2017-01-12 22:36
@hoanglinhlan The extra fields need to be marked as a profile identifier for it to work and the username is case sensitive. It works for me locally. Are you able to confirm the steps to reproduce please?

**Comment by hoanglinhlan** [comment] 2017-01-19 02:29
re-check
confirm it works

**Closed by hoanglinhlan** 2017-01-19 02:29 UTC
Labels: enhancement, Ready to Test - Dev
