### ISSUE TITLE
EDM loading failure on group emails

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4445] opened 2017-11-17 14:11 UTC
![image](https://user-images.githubusercontent.com/1945230/32951260-f7deaa36-cbb1-11e7-8908-cfa680fab7b6.png)
http://vlad-test55.admin.kademi-ci.co/groupEmails/2025672/#messages-tab

**Comment by bradmac** [comment] 2017-11-18 01:51
Closing, duplicate of https://github.com/Kademi/kademi-dev/issues/4394

**Closed** 2017-11-20 07:09 UTC
Labels: bug
