### ISSUE TITLE
KCRM:  Notes should appear after being added

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1223] opened 2016-01-24 06:01 UTC
If you are on the Notes tab and add a note, it should appear after the note is added.  However if you are else where in the CRM it should not automatically go to the notes page.

![image](https://cloud.githubusercontent.com/assets/2201340/12534778/c3e97176-c2a2-11e5-89f3-5dbf672e2938.png)

**Comment by tuzzmaniandevil** [comment] 2016-01-24 22:14
Duplicate of https://github.com/Kademi/kademi-dev/issues/1215

**Closed by tuzzmaniandevil** 2016-01-24 22:14 UTC
