### ISSUE TITLE
Need to be able to upload profiles into funnels and/or tag them

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2345] opened 2016-09-12 14:36 UTC
http://version1.kcrm.kademi.us/custs/

Need to upload profiles with tags
Need to upload profiles and create leads into a chosen funnel

How do I do this?  If not can we build this in.

**Comment by bradmac** [comment] 2016-09-12 20:41
I think we'll need an extension to allow multiple columns with groups

**Comment by bradmac** [comment] 2016-09-14 03:30
Please add group column support to the profiles importer. Ensure that multiple group cols can be used to add the profile to multiple groups

**Comment by bradmac** [comment] 2016-09-14 03:32
@paddyow as a workaround, use the admin profile importer

**Comment by bradmac** [comment] 2017-06-29 22:31
Duplicate of https://github.com/Kademi/kademi-dev/issues/2381

**Closed by bradmac** 2017-06-29 22:31 UTC
Labels: Project KCRM
