### ISSUE TITLE
Removing the dropzone lib in vendor.js file of the leadman-theme.

### ISSUE THREAD

**Issue by tannguyen3489** [Kademi/kademi-dev#3275] opened 2017-05-25 04:18 UTC
currently, we have a conflict import dropzone lib in leadman-theme and myfile-lib. So, please remove the dropzone-lib in vendor.js file.

![image](https://cloud.githubusercontent.com/assets/1665005/26435783/e090cf86-413b-11e7-87c9-0f52765e7159.png)

**Comment by bradmac** [comment] 2017-05-25 04:25
Duplicate of https://github.com/Kademi/kademi-dev/issues/3271

**Comment by ducdhm** [comment] 2017-05-29 10:52
Reason is we have duplicated id for modal "modal-upload". I have changed id of modal in myfile-lib to `modal-upload-files`

**Closed by ducdhm** 2017-05-29 10:52 UTC
