### ISSUE TITLE
OrgSelector js dowloading error while accessing some pages in admin

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5151] opened 2018-03-19 11:53 UTC
![image](https://user-images.githubusercontent.com/1945230/37594077-d887c822-2b7c-11e8-9e7f-98d1643bde3d.png)
http://vladtest43.admin.kademi-ci.co/reward-store/#rewardStores-tab

**Comment by bradmac** [comment] 2018-03-19 11:57
Same root cause as this - https://github.com/Kademi/kademi-dev/issues/5150

**Comment by Uafinder** [comment] 2018-03-19 12:45
Fresh account:
the same for me
![image](https://user-images.githubusercontent.com/1945230/37596198-16491862-2b84-11e8-81ae-27eb2b5d8aff.png)
http://vladtest43c.admin.kademi-ci.co/

**Comment by bradmac** [comment] 2018-03-19 19:51
Closing, duplicate of https://github.com/Kademi/kademi-dev/issues/5153

**Closed by bradmac** 2018-03-19 19:51 UTC
Labels: bug
