### ISSUE TITLE
Triggers cannot be manually fired

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#636] opened 2015-08-21 03:03 UTC
http://cpaaustralia.admin.olhub.com/autoEmails/day-006-pippa/timerTriggers.html

Looks like the deploy has not fixed this.

**Comment by bradmac** [comment] 2015-08-21 03:05
duplicate of https://github.com/Kademi/kademi-dev/issues/629

**Closed by bradmac** 2015-08-21 03:05 UTC
