### ISSUE TITLE
Kademi admin pages crashing Chrome browser

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1609] opened 2016-04-05 23:16 UTC
Chrome Version 49.0.2623.110 m

Loading specific pages causes browser to popup dialogue saying Wait or Close, then it can crash.

http://admin.rspca.olhub.com/emails/  This page sometimes never completes loading
http://admin.rspca.olhub.com/manageUsers/ This page takes a very long time to load and can cause a crash

**Comment by bradmac** [comment] 2016-04-05 23:26
I've seen this too, but only sometimes, and often after the page has been fully loaded.

A couple of times the browser has complained about nice-scroll, so I'm suspicious that plugin is causing the problem for larger pages.

**Comment by bradmac** [comment] 2016-04-05 23:29
"http://admin.w6rb.olhub.com/groups/ this page takes a long time to load and can cause a crash " - Is a different issue, i think. Note that it is a big page (727K), because the options are generated for each group.

This page can be refactored to only use one set of lists for roles and programs, etc

**Comment by ducdhm** [comment] 2016-04-11 09:48
@bradmac Can we close this issue and if we can find how to reproduce it, we'll create other issue?

**Comment by bradmac** [comment] 2016-04-13 00:31
@ducdhm definitely as issue. I just had FF crashed on this page http://admin.cpaaustralia.olhub.com/smsHistory

**Comment by bradmac** [comment] 2016-04-13 00:32
@ducdhm definitely as issue. I just had FF crashed on this page http://admin.cpaaustralia.olhub.com/smsHistory

**Comment by bradmac** [comment] 2016-04-13 00:38
Tried to capture performance stats, but the crash killed it.

NOTE: the screen doesnt have until 1-2 mins after its opened!

**Comment by ducdhm** [comment] 2016-04-13 15:28
@bradmac Can you deploy on beta for me? I updated nicescroll and seem like new version has option for disable MutantObserver, the event handle which will be called when DOM is changed, window is changed or resized

**Comment by ducdhm** [comment] 2016-04-14 11:55
@bradmac It's not crashed in FF. Can you double-check again in your side?

**Closed** 2016-04-14 20:16 UTC
Labels: bug
