### ISSUE TITLE
Separate test and real email in groupEmail, scheduledEmail and automation

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#1084] opened 2015-12-09 05:06 UTC
It's a request from Lee at CPA. Our @paddyow tested a lot and then made their data is incorrect. They need to download CSV and manually delete all Paddy's email records and re-calculate %.

Example: http://cpaaustralia.admin.olhub.com/autoEmails/40396569/#history-tab

**Comment by bradmac** [comment] 2015-12-09 06:40
What we can do is to have the ability to mark emails as ignored from the email history page. That can then remove them from stats.

**Comment by ducdhm** [comment] 2015-12-09 09:23
Yeah, I :+1: this solution. Need indicator if email is test email.

**Comment by bradmac** [comment] 2015-12-09 09:25
I think the easiest thing is just to be able to mark them as ignored. They're not specifically test emails, you might ignore them for any reason.

**Comment by tuzzmaniandevil** [comment] 2015-12-09 20:12
Is this a duplicate of https://github.com/Kademi/kademi-dev/issues/1051 ?

**Comment by tuzzmaniandevil** [comment] 2015-12-09 21:32
Using Issue #1051 
Closing this.

**Closed by tuzzmaniandevil** 2015-12-09 21:32 UTC
Labels: duplicate, enhancement
