### ISSUE TITLE
Closing lead caused error page

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2007] opened 2016-06-17 00:34 UTC
Closing this lead http://kcrm.olhub.com/leads/128090874/

Created this error message on a blank page: {"data":null,"fieldMessages":[],"messages":["Closed deal"],"nextHref":"","status":true}

But the lead was closed.

**Comment by ducdhm** [comment] 2016-06-17 02:43
Can you re-check again? I can't reproduce this issue

**Comment by paddyow** [comment] 2016-06-17 05:04
I just re-opened it and cancelled it again but it went through.  Does the error tell you anything?

**Comment by bradmac** [comment] 2016-06-17 05:06
The "error" is actually just the response from the server but its normally handled by js. This can happen if the page doesnt load properly, or if part of the page is reloaded usually by doing some other action, eg adding a note.

So if you can remember what you did just before that then we might be able to reproduce the error

**Comment by paddyow** [comment] 2016-06-17 05:44
I simply cancelled the lead.  I re-opened the lead and cancelled it again but could not reproduce it.  I have seen this screen many times before but have not consistently been able to re-create it yet.

**Comment by bradmac** [comment] 2016-06-17 05:46
So you've seen this problem many times?

**Comment by paddyow** [comment] 2016-06-17 05:52
I have seen this appear 3 or 4 times before but have never been able to re-produce it.

**Comment by bradmac** [comment] 2016-06-17 05:54
ok, so probably not specific to closing a lead then. If you see it again, then try to write down the exact steps leading up to it.

**Comment by Uafinder** [comment] 2016-06-29 20:09
https://github.com/Kademi/kademi-dev/issues/2072

**Comment by anhnt** [comment] 2016-07-11 10:40
this one looks like fixed. tried many times and cant reproduce. Its just client side issue and was fixed in other issue i think

**Closed by anhnt** 2016-07-11 10:40 UTC
Labels: Project KCRM, question
