### ISSUE TITLE
A Users > Roles to access Asset manager

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#5624] opened 2018-07-02 04:14 UTC
I was talking with Anh on support and we discovered that there is no combination or Roles (other than Administrator) that allows editing of Content > Asset manager.

I can fine grain control of Edit web pages, Edit Translations, Blogs, Groups and Users, Talk & Connect, but not Asset manager.

Normally this would be fine except in this case we are using Asset manager to help better manage our multilingual content.

And so have now given client access to Administrator which gives them access to everything. Not always ideal.

**Comment by bradmac** [comment] 2018-07-02 05:14
:+1:

**Comment by bradmac** [comment] 2018-07-02 05:59
I think it makes sense to hang this off content author rather then adding a new role

**Comment by bradmac** [comment] 2018-07-02 06:40
Oh, i think i midunderstood. 

Access to asset manager is currently controlled by the Content Author role. This role provides access to various types of content which is as intended

![image](https://user-images.githubusercontent.com/826458/42148734-74458194-7e27-11e8-8907-5b6d81eae9b2.png)


![image](https://user-images.githubusercontent.com/826458/42148706-609de370-7e27-11e8-9649-0ab30cd19e97.png)

**Comment by bradmac** [comment] 2018-07-02 06:41
Except i can see this doesnt allow access to edit translations, so i'll add that

**Comment by bradmac** [comment] 2018-07-02 06:45
OK, and i can see that for other pages the menu is correct but access is being denied

**Comment by bradmac** [comment] 2018-07-02 10:46
Those access problems should be fixed now, and i've removed content types from the menu for content authors, since its more of a coding/config thing
![image](https://user-images.githubusercontent.com/826458/42159968-bafeb0ca-7e49-11e8-94c5-0f820e75e632.png)

**Closed** 2018-07-02 10:48 UTC
