### ISSUE TITLE
Completing task creates error page

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2358] opened 2016-09-13 09:43 UTC
http://clickstart-digital-crm.kademi.com.au/leads/21965207/

Click the first tick button on a task in the RHS panel
Click the 2nd tick button
Then the 3rd without adding any additional information

**Comment by ducdhm** [comment] 2016-09-13 19:36
@bradmac I got this error message when reproducing this issue on local

```
ERROR io.milton.cloud.server.web.templating.SimpleHtmlTemplater  - ex
org.apache.velocity.exception.MethodInvocationException: Invocation of method 'getAllFunnels' in  class com.fuselms.apps.leadman.LeadPage threw exception java.lang.NullPointerException at locallead.loopbackdns.com:/theme/apps/leadman/viewLead.html[line 317, column 88]
	at org.apache.velocity.runtime.parser.node.ASTIdentifier.execute(ASTIdentifier.java:223)
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:280)
	at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:567)
	at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:318)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.directive.Block.render(Block.java:82)
	at org.apache.velocity.runtime.directive.Block$Reference.render(Block.java:161)
	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:414)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.directive.VelocimacroProxy.render(VelocimacroProxy.java:216)
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:311)
	at org.apache.velocity.runtime.directive.BlockMacro.render(BlockMacro.java:121)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
	at org.apache.velocity.Template.merge(Template.java:356)
	at org.apache.velocity.Template.merge(Template.java:260)
	at io.milton.cloud.server.web.templating.TextTemplater.writePage(TextTemplater.java:159)
	at io.milton.cloud.server.web.templating.TextTemplater.writePage(TextTemplater.java:128)
	at io.milton.cloud.server.web.templating.SimpleHtmlTemplater.writePage(SimpleHtmlTemplater.java:149)
	at io.milton.cloud.server.web.templating.SimpleHtmlTemplater.writePage(SimpleHtmlTemplater.java:101)
	at io.milton.cloud.server.web.templating.ThemeDependentHtmlTemplater.writePage(ThemeDependentHtmlTemplater.java:42)
	at com.fuselms.apps.leadman.LeadPage.sendContent(LeadPage.java:498)
	at io.milton.http.CompressingResponseHandler.respondContent(CompressingResponseHandler.java:116)
	at io.milton.http.AbstractWrappingResponseHandler.respondContent(AbstractWrappingResponseHandler.java:89)
	at io.milton.http.http11.GetHandler.sendContent(GetHandler.java:220)
	at io.milton.http.http11.GetHandler.processExistingResource(GetHandler.java:84)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:187)
	at io.milton.http.http11.GetHandler.processResource(GetHandler.java:66)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:118)
	at io.milton.http.http11.GetHandler.process(GetHandler.java:60)
	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
	at io.milton.context.RootContext.execute(RootContext.java:83)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at co.kademi.server.Kademi$1.service(Kademi.java:196)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.fuselms.apps.leadman.LeadPage.getAllFunnels(LeadPage.java:803)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.velocity.runtime.parser.node.PropertyExecutor.execute(PropertyExecutor.java:142)
	at org.apache.velocity.util.introspection.UberspectImpl$VelGetterImpl.invoke(UberspectImpl.java:539)
	at org.apache.velocity.runtime.parser.node.ASTIdentifier.execute(ASTIdentifier.java:198)
	... 42 more
```

**Comment by bradmac** [comment] 2016-09-13 20:45
@ducdhm just fyi, that will be because of an error with the funnel, meaning it cant be parsed.

**Comment by tuzzmaniandevil** [comment] 2016-09-13 22:10
@paddyow I tried the steps on the link you sent me with sam as the user, It's working fine.

**Comment by bradmac** [comment] 2016-09-13 22:26
@paddyow I cant follow your steps. There is no third tick, I can only see a "Done" button. But i cannot click the Done button without entering further information, because the description field is required.

When i enter something in the description and press Done everything works fine.

Please provide sufficient information for us to be able to reproduce the problem, otherwise we cant help.

BTW, as a suggestion, open Firebug or the dev tools window, and check for js errors prior to seeing the error window. If you see anything take a screenshot and add it.

**Comment by paddyow** [comment] 2016-09-14 04:28
I opened this form http://clickstart-digital.kademi.com.au/customer.html and filled it out.

I took the 3 tasks that appeared in KCRM.
![image](https://cloud.githubusercontent.com/assets/2201340/18499992/2508eda0-7a87-11e6-9a5b-850fa37b3112.png)

I opened the new lead http://clickstart-digital-crm.kademi.com.au/leads/21996932/ 

I click on the 1st task setup website domain:
![image](https://cloud.githubusercontent.com/assets/2201340/18500017/4a570812-7a87-11e6-8a51-9d7f93f6964f.png)

I click the 2nd tick:
![image](https://cloud.githubusercontent.com/assets/2201340/18500025/59bae4fe-7a87-11e6-84b8-ecef36855ec0.png)

then I click done:
![image](https://cloud.githubusercontent.com/assets/2201340/18500029/6767d2f6-7a87-11e6-9e5e-e117a51d0bdb.png)

Then I get this error page:
![image](https://cloud.githubusercontent.com/assets/2201340/18500046/78105614-7a87-11e6-83e8-d00344f81a23.png)

I will now look at Firebug as I use Chrome.

**Comment by bradmac** [comment] 2016-09-14 04:39
Fixed by clearing cache

**Closed by bradmac** 2016-09-14 04:39 UTC
Labels: bug
