### ISSUE TITLE
Twin search panels on empty clear site

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1388] opened 2016-02-29 18:51 UTC
![image](https://cloud.githubusercontent.com/assets/1945230/13405232/21a341a8-df26-11e5-84cd-7628cb1d44aa.png)
http://vlad4.olhub.com/dashboard

**Comment by anhnt** [comment] 2016-03-03 04:22
just created new clean site which uses bs335 and cant reproduce that issue http://version1.testanh.olhub.com/dashboard. @Uafinder could you tell me more detail about this bug?

**Comment by anhnt** [comment] 2016-03-03 04:39
i think i can reproduce that issue now. the second search box appears because of leadman app gets enabled

**Comment by anhnt** [comment] 2016-03-03 04:44
so i think when using leadman app, user should use bs335.leadman theme that built-in supports leadman features

**Comment by bradmac** [comment] 2016-03-03 04:55
yes, there is a specific leads search box. But we might change that in future, and have a consolidated omnisearch

**Comment by bradmac** [comment] 2016-03-03 04:55
But for the moment its correct to have 2 search boxes

**Comment by anhnt** [comment] 2016-03-03 06:09
ok close this for now. we will reopen if needs to change then

**Closed by anhnt** 2016-03-03 06:09 UTC
Labels: bug
