### ISSUE TITLE
Entry fields do not have a drop down field

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4818] opened 2018-01-22 01:43 UTC
Hey
The entry fields should have a drop-down field to select from, please can we add them

http://ant15.admin.kademi-ci.co/funnels/first-journey/version1/#journeyBuilder-tab
http://ant15.admin.kademi-ci.co/funnels/

![entry field issue](https://user-images.githubusercontent.com/32444328/35201730-9ad021a8-ff82-11e7-9cc4-1752cf7fec5a.png)

**Comment by bradmac** [comment] 2018-01-22 02:04
FYI, these are the allowable values for action

```
        MODULE_STARTED, // fired when a module has been started
        MODULE_COMPLETE, // fired when a module has been completed
        MODULE_LANGUISHING, // fired when a module has been started, but not completed after some time
        MODULE_SAVED, // Called when a module is updated by the learner
        RENEWAL, // when a completed module enters its renewal period
        EXPIRED, // when a completed module expires
        SUBMITTED // when a learner submits a module, eg an assignment, or attends an ILT class
```

**Comment by bradmac** [comment] 2018-01-22 02:05
Duplicate of https://github.com/Kademi/kademi-dev/issues/3996

**Closed by bradmac** 2018-01-22 02:05 UTC
