### ISSUE TITLE
Summary tab on user profile should react on date range picker

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6563] opened 2019-01-16 10:53 UTC
There are a lot of accounts which has a long story and their profile loading very very long.
We should limit summary tab display to date range limits. or we need to implement some pagination to summary page.
For example this account
https://mhiaainstaller.admin.kademi.com.au/manageUsers/126910306/#summary-tab

**Comment by bradmac** [comment] 2019-01-16 21:16
Duplicate of https://github.com/Kademi/kademi-dev/issues/2347

**Closed by bradmac** 2019-01-16 21:16 UTC
Labels: Discuss, enhancement
