### ISSUE TITLE
KCRM: Companies list page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5847] opened 2018-08-19 22:53 UTC
![image](https://user-images.githubusercontent.com/826458/44314024-4752de00-a467-11e8-853c-6cc76594e44f.png)

**Comment by bradmac** [comment] 2018-08-19 22:55
@anhnt please just update the table style to match the layout:
![image](https://user-images.githubusercontent.com/826458/44314032-83863e80-a467-11e8-8d24-4b874bca4e31.png)

Also, i think we can remove "view details" and instead make the title a link

**Comment by anhnt** [comment] 2018-08-21 06:12
@bradmac please help adding api to delete company

![image](https://user-images.githubusercontent.com/735555/44383720-daf9dc80-a543-11e8-9665-18b7111ea66d.png)

**Comment by bradmac** [comment] 2018-08-22 01:45
@anhnt updated, just POST to /companies/ with list parameter "companyId"

Also, please move JS out of the component html file. All handler JS should be in a JS file referenced from dependencies

**Comment by anhnt** [comment] 2018-08-22 09:43
i got error when deleting companies

```
ERROR- co.kademi.server.logging.KademiSimpleJdbcEventListener  - SQL Exception: delete from org_entity where id=723
WARN - org.hibernate.engine.jdbc.spi.SqlExceptionHelper  - SQL Error: 23003, SQLState: 23003
ERROR- org.hibernate.engine.jdbc.spi.SqlExceptionHelper  - Referential integrity constraint violation: "FK_DDBUKRPBUO9FJU5B742V9Q3GG: PUBLIC.LEAD FOREIGN KEY(ORGANISATION) REFERENCES PUBLIC.ORG_ENTITY(ID)"; SQL statement:
delete from org_entity where id=? [23003-144]
ERROR- io.milton.cloud.util.SessionManagerUtils  - Exception processing: command io.milton.cloud.util.Command@2861a214
org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:129)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:189)
	at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3358)
	at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3558)
	at org.hibernate.action.internal.EntityDeleteAction.execute(EntityDeleteAction.java:102)
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:393)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:385)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:308)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:349)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1159)
	at com.fuselms.apps.leadman.LeadmanService.deleteLeadCompany(LeadmanService.java:720)
	at com.fuselms.apps.leadman.LeadCompaniesFolder.deleteCompanies(LeadCompaniesFolder.java:83)
	at io.milton.cloud.util.SessionManagerUtils.apply(SessionManagerUtils.java:228)
	at io.milton.cloud.util.SessionManagerUtils.processFormCommandInTransaction(SessionManagerUtils.java:189)
	at com.fuselms.apps.leadman.LeadCompaniesFolder.processForm(LeadCompaniesFolder.java:69)
	at io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
	at io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
	at io.milton.http.http11.PostHandler.process(PostHandler.java:62)
	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:48)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:43)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
	at io.milton.context.RootContext.execute(RootContext.java:90)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at co.kademi.server.webcache.KademiWebCacheFilter.process(KademiWebCacheFilter.java:125)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at co.kademi.server.Kademi$1.service(Kademi.java:194)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: Referential integrity constraint violation: "FK_DDBUKRPBUO9FJU5B742V9Q3GG: PUBLIC.LEAD FOREIGN KEY(ORGANISATION) REFERENCES PUBLIC.ORG_ENTITY(ID)"; SQL statement:
delete from org_entity where id=? [23003-144]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:382)
	at org.h2.constraint.ConstraintReferential.checkRowRefTable(ConstraintReferential.java:399)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:275)
	at org.h2.table.Table.fireConstraints(Table.java:813)
	at org.h2.table.Table.fireAfterRow(Table.java:830)
	at org.h2.command.dml.Delete.update(Delete.java:80)
	at org.h2.command.CommandContainer.update(CommandContainer.java:69)
	at org.h2.command.Command.executeUpdate(Command.java:201)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:143)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:129)
	at com.p6spy.engine.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:95)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:186)
	... 37 more

**Comment by bradmac** [comment] 2018-08-22 23:55
I think that error was occuring when there was a deleted, cancelled or closed lead related to the company being deleted.

I've applied a fix so these should now get unlinked prior to deleting the company

**Comment by anhnt** [comment] 2018-08-23 01:45
@bradmac i am still getting that error. Please check

**Comment by Uafinder** [comment] 2018-08-27 12:13
1. Search doesn't work
![image](https://user-images.githubusercontent.com/1945230/44658196-90c3a000-aa08-11e8-9ab3-d23510d6f272.png)
http://vladtest53ssweb-vladtest53ss.kademi-ci.co/companies
Using search broke page

2. members column show a direct members for companies.
not sure that this information is useful for kcrm
it could be more useful when showing leads for a company
![image](https://user-images.githubusercontent.com/1945230/44658267-dd0ee000-aa08-11e8-9f01-f01921b30104.png)
just asking

3. No create company button
![image](https://user-images.githubusercontent.com/1945230/44658306-00d22600-aa09-11e8-818c-b7713457b145.png)
![image](https://user-images.githubusercontent.com/1945230/44658314-0cbde800-aa09-11e8-9c01-ed6c23330d07.png)

4. Reproduced error for deletion company, company has assigned member (membership not null). Message should appear or error should be fixed.
14:59:28 ERROR co.kademi.server.logging.KademiSimpleJdbcEventListener  - SQL Exception: delete from org_entity where id=17746737
14:59:28 WARN  org.hibernate.engine.jdbc.spi.SqlExceptionHelper  - SQL Error: 0, SQLState: 23503
14:59:28 ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper  - ERROR: update or delete on table "org_entity" violates foreign key constraint "fk_j4ldk8unv1bajr5kn2812ircp" on table "group_membership"
14:59:28   Detail: Key (id)=(17746737) is still referenced from table "group_membership".
14:59:28 INFO  co.kademi.server.stream.audit.KademiAuditService  - tx complete tx=539249037 updates=1 creates=0 loads=0
14:59:28 ERROR io.milton.cloud.util.SessionManagerUtils  - Exception processing: command io.milton.cloud.util.Command@2bea34be
14:59:28 org.hibernate.exception.ConstraintViolationException: could not execute statement
14:59:28 	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:129)
14:59:28 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
14:59:28 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
14:59:28 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
14:59:28 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:189)
14:59:28 	at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3358)
14:59:28 	at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3558)
14:59:28 	at org.hibernate.action.internal.EntityDeleteAction.execute(EntityDeleteAction.java:102)
14:59:28 	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:393)
14:59:28 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:385)
14:59:28 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:308)
14:59:28 	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:349)
14:59:28 	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
14:59:28 	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1159)
14:59:28 	at com.fuselms.apps.leadman.LeadmanService.deleteLeadCompany(LeadmanService.java:728)
14:59:28 	at com.fuselms.apps.leadman.LeadCompaniesFolder.deleteCompanies(LeadCompaniesFolder.java:83)
14:59:28 	at io.milton.cloud.util.SessionManagerUtils.apply(SessionManagerUtils.java:228)
14:59:28 	at io.milton.cloud.util.SessionManagerUtils.processFormCommandInTransaction(SessionManagerUtils.java:189)
14:59:28 	at com.fuselms.apps.leadman.LeadCompaniesFolder.processForm(LeadCompaniesFolder.java:69)
14:59:28 	at io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
14:59:28 	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
14:59:28 	at io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
14:59:28 	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
14:59:28 	at io.milton.http.http11.PostHandler.process(PostHandler.java:62)
14:59:28 	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
14:59:28 	at io.milton.http.FilterChain.process(FilterChain.java:46)
14:59:28 	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:48)
14:59:28 	at io.milton.http.FilterChain.process(FilterChain.java:46)
14:59:28 	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:43)
14:59:28 	at io.milton.http.FilterChain.process(FilterChain.java:46)
14:59:28 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
14:59:28 	at io.milton.context.RootContext.execute(RootContext.java:90)
14:59:28 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
14:59:28 	at io.milton.http.FilterChain.process(FilterChain.java:46)
14:59:28 	at co.kademi.server.webcache.KademiWebCacheFilter.process(KademiWebCacheFilter.java:125)
14:59:28 	at io.milton.http.FilterChain.process(FilterChain.java:46)
14:59:28 	at io.milton.http.HttpManager.process(HttpManager.java:158)
14:59:28 	at co.kademi.server.Kademi$1.service(Kademi.java:194)
14:59:28 	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
14:59:28 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
14:59:28 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
14:59:28 	at java.lang.Thread.run(Thread.java:748)
14:59:28 Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "org_entity" violates foreign key constraint "fk_j4ldk8unv1bajr5kn2812ircp" on table "group_membership"
14:59:28   Detail: Key (id)=(17746737) is still referenced from table "group_membership".
14:59:28 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
14:59:28 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
14:59:28 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
14:59:28 	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
14:59:28 	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420)
14:59:28 	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:366)
14:59:28 	at com.p6spy.engine.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:95)
14:59:28 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:186)
14:59:28 	... 37 more

5. When you delete company from KCRM portal, this org still appears in list of groups for assignments
![image](https://user-images.githubusercontent.com/1945230/44659036-835be500-aa0b-11e8-9472-7a8cbb8cbb61.png)
![image](https://user-images.githubusercontent.com/1945230/44659049-8fe03d80-aa0b-11e8-8209-6aea0f4b222b.png)
![image](https://user-images.githubusercontent.com/1945230/44659064-9a023c00-aa0b-11e8-9ae1-7374eba1566f.png)
When delete org via admin console - all seems to be normal

**Comment by bradmac** [comment] 2018-08-27 23:30
> members column show a direct members for companies.. not sure that this information is useful for kcrm

I think its appropriate to show members rather then leads.

**Comment by bradmac** [comment] 2018-08-27 23:34
@anhnt please resolve other issues above

**Comment by anhnt** [comment] 2018-08-29 03:39
Done

**Comment by Uafinder** [comment] 2018-08-29 08:27
1. Adding company cause an error
![image](https://user-images.githubusercontent.com/1945230/44775412-36e4e680-ab7e-11e8-8bf5-0ac001c8e0d0.png)
Could be a permission issue (kcrmadmin user). Was the same when editing company details.
http://vladtest53tweb-vladtest53t.kademi-ci.co/companies/

2. Using search cause sorting not worked
E.g. try to search something, then clear search field, try to sort something and it will not be workable.
http://vladtest53tweb-vladtest53t.kademi-ci.co/companies/

**Comment by anhnt** [comment] 2018-08-29 08:46
Done

**Comment by Uafinder** [comment] 2018-08-29 10:09
Ok, looks good

**Closed by Uafinder** 2018-08-29 10:09 UTC
Labels: Ready to Test - Dev, bug
