### ISSUE TITLE
Time out at specific time using the JB

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2427] opened 2016-09-23 12:48 UTC
I want to  send an email at a specific time and delay.  Can this be added as a feature.

![image](https://cloud.githubusercontent.com/assets/2201340/18786137/b945ed9c-81df-11e6-8189-6bbbab669996.png)

**Comment by bradmac** [comment] 2016-09-25 21:45
Closing, duplicate of https://github.com/Kademi/kademi-dev/issues/2393

**Closed by bradmac** 2016-09-25 21:45 UTC
Labels: enhancement
