### ISSUE TITLE
Query table component not picking up query's

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4854] opened 2018-01-25 22:16 UTC
When a query has been made, and you config the setting in the query table component.
the problem is that the when you log onto the dashboard, you cant see any data.

http://version1.onboarding-journey_ant15.kademi-ci.co/queries/managers-info/?run&from=0&size=100

http://version1.onboarding-journey_ant15.kademi-ci.co/dashboard
http://ant15.admin.kademi-ci.co/pages/onboarding-journey/version1/
http://ant15.admin.kademi-ci.co/queries/managers-info/#queryBuilderTab-tab
![a](https://user-images.githubusercontent.com/32444328/35415397-4e5aee92-028a-11e8-9ebc-bc2405e2e6c7.png)

**Comment by bradmac** [comment] 2018-02-27 04:36
Working now..
![image](https://user-images.githubusercontent.com/826458/36710716-a230c1c2-1be4-11e8-890c-8c8497e2ff8a.png)

**Comment by bradmac** [comment] 2018-02-27 04:44
@Uafinder to test this, please create a query, and then select it from a table component in keditor as above

here's an example query..

![image](https://user-images.githubusercontent.com/826458/36710950-d02919ca-1be5-11e8-946e-0f76c4268a3e.png)

![image](https://user-images.githubusercontent.com/826458/36710966-da1daae0-1be5-11e8-8efc-f2bf1cb911ec.png)

**Comment by Uafinder** [comment] 2018-03-01 13:54
Doesn't work for my query:
![image](https://user-images.githubusercontent.com/1945230/36848024-b1d7d7f2-1d68-11e8-9360-35a7b67cfec5.png)
http://vladtest38a.admin.kademi-ci.co/pages/vladtest38aaucstore/version1/?contenteditor=page1.html
Query
![image](https://user-images.githubusercontent.com/1945230/36848057-c80182f8-1d68-11e8-9dfe-73829d5d2387.png)
http://vladtest38a.admin.kademi-ci.co/queries/querypoints/#queryBuilderTab-tab

**Comment by bradmac** [comment] 2018-03-01 19:05
hey @Uafinder its not required for data to display in the editor. The data should display correctly when the page is viewed.

**Comment by Uafinder** [comment] 2018-03-02 09:36
It's not a point... it's even not showing column names
But, anyway I checked on the page and doesn't see query result as well
![image](https://user-images.githubusercontent.com/1945230/36892580-db4a5100-1e0d-11e8-8031-456794e5c9ed.png)

**Comment by bradmac** [comment] 2018-03-04 19:58
Libs had not been updated:
![image](https://user-images.githubusercontent.com/826458/36949908-30b3ba04-2053-11e8-82a9-e6b8d3e4739c.png)

After updating libs i needed to reselect the query in the component. 

![image](https://user-images.githubusercontent.com/826458/36949923-4e7e0cd8-2053-11e8-88b0-a475fe28ec97.png)

**Comment by Uafinder** [comment] 2018-03-05 13:32
Ok, the problem is that query component doesn't show headers and CSV button. E.g.
![image](https://user-images.githubusercontent.com/1945230/36977093-ad9b5ca4-2088-11e8-9b3f-8968843c40b9.png)
When you click to query table and back in component settings headers and CSV button appears
![image](https://user-images.githubusercontent.com/1945230/36977603-6bfb0ba8-208a-11e8-8822-ccb413d367d5.png)
http://vladtest38d.admin.kademi-ci.co/pages/vladtest38daucstore/version1/

**Comment by bradmac** [comment] 2018-03-05 20:05
Hi @Uafinder about this:

> When you click to query table and back in component settings headers and CSV button appears

So it sounds like the problem described in this issue is resolved.  If you agree then please close the issue.

If there is a seperate issue related to displaying headers in the editor then please create that as a new issue which is a much lower priority then this one.

**Comment by Uafinder** [comment] 2018-03-06 12:15
Moved to separate issue
Mostly is ok!

**Closed by Uafinder** 2018-03-06 12:15 UTC
Labels: Discuss, Ready to Test - Dev, bug
