### ISSUE TITLE
Blog article issue

### ISSUE THREAD

**Issue by yrsengar** [Kademi/kademi-dev#6438] opened 2018-12-18 02:41 UTC
Unpublished all articles. Opened one up to edit. Changed the title / added content (the boxes were there to put content into) / added an image + changed the image name. Clicked ‘save changes’ when I completed each of the three tasks above. When I go back to the ‘content’ tab – everything is gone. The title is back to original. The content is all gone (there’s no containers). The image is back to the original.

Site URL: http://hazero-hazero.kademi.com.au/

**Comment by bradmac** [comment] 2018-12-18 03:14
I edited this article:

http://hazero.admin.kademi.com.au/blogs/case-studies/the-milk-factory/

- i set the title
- added an image
- set the content

I've refreshed the page and verified the content is still as i saved it.

Can you please describe the steps i should follow to see the problem?

**Comment by bradmac** [comment] 2018-12-21 04:36
Removing from milestone. @yrsengar if you do still see an issue please provide steps to reproduce the problem

**Comment by joelatfuel** [comment] 2019-01-09 03:02
Hi @bradmac,

Can we reopen this? The client is still experiencing this error so I asked her to send a video.
https://drive.google.com/file/d/1sIer4BMCI3brmfQxFXpM3fCeDdh5ERac/view?usp=sharing

**Comment by bradmac** [comment] 2019-01-09 03:37
@Uafinder please review the video above and see if you can reproduce the issue

**Comment by Uafinder** [comment] 2019-01-21 12:55
I was not able to reproduce a problem...
But i have an idea that affected article was modified as plain text and when you try to edit it via Keditor it can't recognize already modified source.
I haven't experiment on live article so not sure about that theory.

**Comment by bradmac** [comment] 2019-01-21 20:05
@joelatfuel please see Vlad's comment above, and discuss with your client accordingly

**Comment by bradmac** [comment] 2019-01-21 20:06
I think that to solve the problem, we need your client to use kademi's instant chat when they see the issue, and BEFORE they save any changes

**Comment by bradmac** [comment] 2019-01-21 20:07
So i'll close this issue for now, it might be reopened if we can get actionable information from the client

**Closed by bradmac** 2019-01-21 20:07 UTC
Labels: Discuss
