### ISSUE TITLE
Unsubscribe does not work

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5109] opened 2018-03-13 03:39 UTC
This profile pharmytest@mailinator.com is in the unsub list here http://kademi.admin.kademi.us/unsubscribes/

The profile was created again manually and started in a journey.   They were subsequently sent an email which is incorrect as they were in the unsub list.

http://kademi.admin.kademi.us/manageUsers/20707223/#summary-tab

- If a profile is manually created but has an email in the unsub list, they should not be created again.  The admin would need to go to the unsub list and re-subscribe the profile
- If a profile is created from a file upload any profiles in the unsub list should be returned as errors and downloaded
- If a profile is created from a contact, rego form for example, they would be re-subscribing so this should be allowed

**Comment by gonzalon** [comment] 2018-03-15 03:17
Added the validation when you are creating a user manually or by an import.

**Comment by Uafinder** [comment] 2018-03-21 13:18
> If a profile is manually created but has an email in the unsub list, they should not be created again. The admin would need to go to the unsub list and re-subscribe the profile
It ok

> If a profile is created from a file upload any profiles in the unsub list should be returned as errors and downloaded
Also ok

> If a profile is created from a contact, rego form for example, they would be re-subscribing so this should be allowed
when user in renewing his subscription for example via contact form it will create a duplicate of account - not enabling an old one. This may cause a lot of probs
Newly created
![image](https://user-images.githubusercontent.com/1945230/37711843-c4a5c4cc-2d1a-11e8-9ffe-ccc4bb3fccb3.png)
Disabled
![image](https://user-images.githubusercontent.com/1945230/37711874-de57bb64-2d1a-11e8-911a-274ab1a30175.png)
http://vladtest45.admin.kademi-ci.co/manageUsers/?q=&g&enabled=true

**Comment by bradmac** [comment] 2018-03-21 21:29
> If a profile is created from a contact, rego form for example, they would be re-subscribing so this should be allowed

I disagree. Anyone can enter anyone else's email address in a contact form.

If someone has unsubbed that means they definitely do not want to be contacted again and we must honour that.

**Comment by bradmac** [comment] 2018-03-21 21:30
If we did want to allow re-subscribing from contact forms we would need to implement an email verification process. Thats not in scope at the moment.

**Comment by bradmac** [comment] 2018-04-23 23:54
Sarah at Travelworld has reported a problem where users are being re-imported after unsubbing, and this is creating a new profile which the unsub isnt blocking.

**Comment by bradmac** [comment] 2018-04-23 23:56
I've pushed a fix to block sending to users by email address, even if there is a new profile

**Comment by bradmac** [comment] 2018-04-23 23:58
> when user in renewing his subscription for example via contact form it will create a duplicate of account - not enabling an old one. This may cause a lot of probs


No, this behaviour is correct. The disabled account could have private data which a new user would get access to if it was re-enabled. Disabled accounts should be considered deleted for all practical purposes, unless explicitly re-enabled by an admin

**Comment by bradmac** [comment] 2018-04-23 23:59
Note this is a client facing issue now - http://kcrm.kademi.us/leads/47017364/

**Comment by Uafinder** [comment] 2018-04-24 10:13
Looks ok now

**Closed by Uafinder** 2018-04-24 10:13 UTC
Labels: High priority, Ready to Test - Dev, bug
