### ISSUE TITLE
KCRM customer search not working for email

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4991] opened 2018-02-17 01:39 UTC
http://kcrm.kademi.us/custs/

Search for this profiles email first http://kademi.admin.kademi.us/manageUsers/16267668/#general-tab
It returns no result

Then try searching for the profiles first and last name, his profile appears.

**Comment by bradmac** [comment] 2018-02-18 19:18
Confirmed

**Comment by bradmac** [comment] 2018-02-18 21:25
Fixed. Needs search-lib 1.1.4

**Comment by Uafinder** [comment] 2018-02-19 11:13
Still doesn't work
![image](https://user-images.githubusercontent.com/1945230/36375111-a7cde304-1576-11e8-9fd1-b198b043fe13.png)
![image](https://user-images.githubusercontent.com/1945230/36375115-af22f5fe-1576-11e8-8fc7-ec5901914b1a.png)
http://version1.vladtest35leads-vladtest35.kademi-ci.co/custs
http://vladtest35.admin.kademi-ci.co/websites/

**Comment by bradmac** [comment] 2018-02-19 19:54
OK, problem now is slightly different. In this account there are no leads, only contacts. But looks like contacts arent being searched...

**Comment by bradmac** [comment] 2018-02-19 20:54
Fixed. The profile app indexer wasnt being used in front end sites

**Comment by Uafinder** [comment] 2018-02-20 14:10
Still doesn't work for me
Fresh account
![image](https://user-images.githubusercontent.com/1945230/36428392-73125bf8-1658-11e8-994d-2dcfea5acd60.png)
![image](https://user-images.githubusercontent.com/1945230/36428420-82351f6c-1658-11e8-86f5-e612889636f4.png)
![image](https://user-images.githubusercontent.com/1945230/36428400-783d9c1e-1658-11e8-8f45-564e9694285f.png)
http://vladtest35atest1_vladtest35a.kademi-ci.co/custs/

**Comment by bradmac** [comment] 2018-02-20 21:46
Had an incorrect query term for the email field. Fixed now

**Comment by Uafinder** [comment] 2018-02-21 11:47
Looks good

**Closed by Uafinder** 2018-02-21 11:47 UTC
Labels: Ready to Test - Dev, bug
