### ISSUE TITLE
Null error when add admin domain in ORG profile

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4074] opened 2017-10-05 10:22 UTC
![clipboard - october 5 2017 1-13 pm](https://user-images.githubusercontent.com/1945230/31222568-354c3b1c-a9d0-11e7-84f8-f117579a4d10.png)

Adding text with UpperCase cause error.
http://vlad-test10.admin.kademi-ci.co/organisations/208053/edit/

**Comment by anhnt** [comment] 2017-10-05 10:23
error log:
```
class java.lang.reflect.InvocationTargetException::null
- sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
- sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
- sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
- java.lang.reflect.Method.invoke(Method.java:498)
- org.apache.commons.beanutils.PropertyUtilsBean.invokeMethod(PropertyUtilsBean.java:2116)
- org.apache.commons.beanutils.PropertyUtilsBean.setSimpleProperty(PropertyUtilsBean.java:2097)
- org.apache.commons.beanutils.PropertyUtilsBean.setNestedProperty(PropertyUtilsBean.java:1903)
- org.apache.commons.beanutils.PropertyUtilsBean.setProperty(PropertyUtilsBean.java:2010)
- org.apache.commons.beanutils.BeanUtilsBean.setProperty(BeanUtilsBean.java:1011)
- org.apache.commons.beanutils.BeanUtilsBean.populate(BeanUtilsBean.java:821)
- io.milton.cloud.server.web.templating.DataBinder.populate(DataBinder.java:210)
- io.milton.cloud.server.web.templating.DataBinder.populate(DataBinder.java:161)
- io.milton.cloud.server.apps.orgs.EditOrgPage.processForm(EditOrgPage.java:200)
- io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
- io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
- io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
- io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
- io.milton.http.http11.PostHandler.process(PostHandler.java:62)
- io.milton.http.StandardFilter.process(StandardFilter.java:50)
- io.milton.http.FilterChain.process(FilterChain.java:46)
- co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:32)
- io.milton.http.FilterChain.process(FilterChain.java:46)
- co.kademi.server.idp.IDPFilter.process(IDPFilter.java:42)
- io.milton.http.FilterChain.process(FilterChain.java:46)
- io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
- io.milton.context.RootContext.execute(RootContext.java:90)
- io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
- io.milton.http.FilterChain.process(FilterChain.java:46)
- io.milton.http.HttpManager.process(HttpManager.java:158)
- co.kademi.server.Kademi$1.service(Kademi.java:186)
- org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
- org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
- org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
- java.lang.Thread.run(Thread.java:748)
class java.lang.RuntimeException::Admin domain must be all lower case
- io.milton.vfs.db.Organisation.setAdminDomain(Organisation.java:350)
- sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
- sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
- sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
- java.lang.reflect.Method.invoke(Method.java:498)
- org.apache.commons.beanutils.PropertyUtilsBean.invokeMethod(PropertyUtilsBean.java:2116)
- org.apache.commons.beanutils.PropertyUtilsBean.setSimpleProperty(PropertyUtilsBean.java:2097)
- org.apache.commons.beanutils.PropertyUtilsBean.setNestedProperty(PropertyUtilsBean.java:1903)
- org.apache.commons.beanutils.PropertyUtilsBean.setProperty(PropertyUtilsBean.java:2010)
- org.apache.commons.beanutils.BeanUtilsBean.setProperty(BeanUtilsBean.java:1011)
- org.apache.commons.beanutils.BeanUtilsBean.populate(BeanUtilsBean.java:821)
- io.milton.cloud.server.web.templating.DataBinder.populate(DataBinder.java:210)
- io.milton.cloud.server.web.templating.DataBinder.populate(DataBinder.java:161)
- io.milton.cloud.server.apps.orgs.EditOrgPage.processForm(EditOrgPage.java:200)
- io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
- io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
- io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
- io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
- io.milton.http.http11.PostHandler.process(PostHandler.java:62)
- io.milton.http.StandardFilter.process(StandardFilter.java:50)
- io.milton.http.FilterChain.process(FilterChain.java:46)
- co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:32)
- io.milton.http.FilterChain.process(FilterChain.java:46)
- co.kademi.server.idp.IDPFilter.process(IDPFilter.java:42)
- io.milton.http.FilterChain.process(FilterChain.java:46)
- io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
- io.milton.context.RootContext.execute(RootContext.java:90)
- io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
- io.milton.http.FilterChain.process(FilterChain.java:46)
- io.milton.http.HttpManager.process(HttpManager.java:158)
- co.kademi.server.Kademi$1.service(Kademi.java:186)
- org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
- org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
- org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
- java.lang.Thread.run(Thread.java:748)
```

**Comment by bradmac** [comment] 2017-10-05 21:38
Closing, because we're going to refactor that UI anyway. This is expected behaviour at present.

**Closed by bradmac** 2017-10-05 21:38 UTC
Labels: bug

**Comment by bradmac** [comment] 2017-10-05 21:40
To create an admin account either use "Create account" on orgs page:
![image](https://user-images.githubusercontent.com/826458/31253793-a6c6938e-aa82-11e7-9a45-39af68c44c60.png)

or create account from the admin dashboard
