### ISSUE TITLE
Creating module pages

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2795] opened 2017-01-11 09:40 UTC
When adding a new page:
![image](https://cloud.githubusercontent.com/assets/2201340/21843126/edbb8d34-d83d-11e6-92f9-e23564ad1bff.png)

It feels wrong that the old editor opens - especially as I do not want to start editing the content in this only to find out the new editor exsits.  I should be able to create a new page and have it open it in the new editor.  Maybe we have the option to create new page and choose the editor in one?

**Comment by bradmac** [comment] 2017-10-27 02:56
Hey @ducdhm we really should be creating pages with keditor. But i think we might need the overlay editor so its in the same page, rather then opening a new tab

**Comment by ducdhm** [comment] 2017-11-30 06:57
@bradmac You mean we will force to use keditor? At the moment, we have logic code to check keditor or CKEditor which is depended on theme.

**Comment by bradmac** [comment] 2017-11-30 07:25
We still need to support bs335, so we're only talking about new them sites

**Comment by bradmac** [comment] 2017-11-30 21:22
@ducdhm so, for keditor theme sites, lets do it the same as we do for editing web pages. The initial form just creates the page and there is no editor. Once the page is created the user can click on it to edit.

I would like to use an overlay editor, but we can look at that in a later issue.

**Comment by ducdhm** [comment] 2017-12-05 16:01
Fixed!

**Comment by Uafinder** [comment] 2017-12-08 12:41
I've have an error in console while creating a page (it looks non-critical)
![image](https://user-images.githubusercontent.com/1945230/33766218-3a52e30e-dc25-11e7-8792-6234b1bf4783.png)
To reproduce it you should clear cache. Also it could be because keditor loading very slow
1. Push add page
2. page loaded (keditor not)
3. Enter some name
4. Push save

**Comment by ducdhm** [comment] 2017-12-11 07:50
Fixed!

**Comment by Uafinder** [comment] 2017-12-11 10:44
Now, I'm seeing following error:
![image](https://user-images.githubusercontent.com/1945230/33827445-089a98e0-de71-11e7-880c-3b3787fad7ea.png)
Fresh account
http://vladtest03b.admin.kademi-ci.co
http://vladtest03b.admin.kademi-ci.co/websites/vlad03learn/version1/programs/p1/c1/m1/#files-tab

**Comment by anhnt** [comment] 2017-12-20 09:25
It works ok on new website on the same account org http://vladtest03b.admin.kademi-ci.co/websites/testanh/version1/programs/p1/c1/m1/#files-tab

**Comment by anhnt** [comment] 2017-12-20 09:57
as discussed with @bradmac we're just cool if fresh site working ok

**Comment by Uafinder** [comment] 2017-12-20 10:09
same thing for new account and new website
![image](https://user-images.githubusercontent.com/1945230/34201846-873cd974-e57e-11e7-94e1-c93a18835f40.png)
http://vladtest10.admin.kademi-ci.co/websites/vlad10learn2/version1/programs/p1/c1/m1/#files-tab
to see this please clear your cache...

**Comment by bradmac** [comment] 2017-12-20 21:37
@Uafinder works ok for me. Tried clearing cache, and not clearing.

![image](https://user-images.githubusercontent.com/826458/34229927-f0063c54-e63a-11e7-9369-b734e534e8df.png)

**Comment by anhnt** [comment] 2017-12-22 02:36
Working great for me both local and QA

**Comment by Uafinder** [comment] 2017-12-26 10:53
I wrote video for this errors:
- keditor launching very slowly and it may cause save page while it doesn't load completely:
https://drive.google.com/file/d/1FPduTP46CyIIO1_P1K1jWETjCHsWfXGs/view?usp=sharing

- postMessage error
![image](https://user-images.githubusercontent.com/1945230/34354107-b68af32c-ea34-11e7-94d3-a80888b0e28e.png)
https://drive.google.com/file/d/10J5Kpo9iS9z7rV88IUOsv58SO7wRKqFJ/view?usp=sharing

**Comment by bradmac** [comment] 2018-02-05 22:48
hey @anhnt i really want to confirm if this is a genuine problem or not, and then either take action to resolve it or close it.

Please discuss with @Uafinder if you cant reproduce it.

**Comment by anhnt** [comment] 2018-02-06 05:13
In newly created account, when creating new page, it was loading content editor slowly but once its loaded everything works ok

http://anhtest15.admin.kademi-ci.co/websites/w1/version1/programs/p1/c1/m1/#files-tab

**Comment by Uafinder** [comment] 2018-02-06 08:49
problems look obsolete
it loads ok, without any fatal errors...closing this issue

**Closed by Uafinder** 2018-02-06 08:49 UTC
Labels: High priority, bug, enhancement
