### ISSUE TITLE
All Importers: Limit number of rows processed in validation stage

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2608] opened 2016-11-07 11:37 UTC
When in Review step, and admin closed tab, the job to review data to upload should stop. I was testing with 16k rows of data and it was still reviewing data when that page is unloaded

**Comment by bradmac** [comment] 2017-05-07 22:33
The server cant know if the user has closed the tab. But we should have an option to cancel.

And same for other importers

**Comment by bradmac** [comment] 2017-06-29 22:27
@tuzzmaniandevil we just want to be able to cancel imports during the review stage, as well as during the actual import

**Comment by bradmac** [comment] 2018-01-07 20:41
This can be resolved by limiting validation to maxiumum of 1k rows, and extrapolating results

**Comment by tuzzmaniandevil** [comment] 2018-01-08 01:04
Limiting is done, deployed and tested :-)

**Comment by Uafinder** [comment] 2018-01-08 10:11
Looks ok for me...
I suppose that we can't spot errors in rows (>1000) it's an expected behavior.

**Comment by bradmac** [comment] 2018-01-08 20:58
@tuzzmaniandevil as discussed please change the estimation so it skips through the entire file. Eg for a file with 4000 rows it will check every 4th row.

**Comment by tuzzmaniandevil** [comment] 2018-01-08 21:28
All done

**Comment by Uafinder** [comment] 2018-01-09 12:04
Looks much worse...
1. When file contains more than 1000 records it will double a result (new records to be inserted).
![image](https://user-images.githubusercontent.com/1945230/34719979-a1b3e4a6-f545-11e7-9363-5e2c4c5c64cb.png)

2. It doesn't found mistake rows in large file. It contains approx. 10000 rows, so it should check every 10th row. I've corrupt 20 of them to ensure some falls in that limit, but it's not capture them...
[users(6)-10500.zip](https://github.com/Kademi/kademi-dev/files/1614989/users.6.-10500.zip)

http://vladtest20.admin.kademi-ci.co/tableUploaders/usersUploader

**Comment by bradmac** [comment] 2018-01-09 20:56
Same. For an import of 2k rows where 500 already exist:

![image](https://user-images.githubusercontent.com/826458/34742834-83041de4-f5ec-11e7-9447-81c613309b95.png)

**Comment by tuzzmaniandevil** [comment] 2018-01-09 21:50
I've adjusted the math, Looks much better now! Tested with you file and 500 existing profiles:

![image](https://user-images.githubusercontent.com/3378330/34745019-112046b4-f5f4-11e7-8e87-e206f357a923.png)

**Comment by bradmac** [comment] 2018-01-10 20:20
@Uafinder that sounds correct to me. The new process is faster because it only samples rows, and then gives an estimate based on the sample

It will sample 1000 rows, so if you're uploading a file with 10k rows it will sample 1 in every 10 rows.

The "340" is an estimate, and if the real value is 344 then its a very good estimate.

> And it still not predict errors...

I cant say anything about that because i dont know how many errors there are.

Saying

**Comment by Uafinder** [comment] 2018-01-11 08:19
Yeah, just tuned file a  bit and was able to catch errors
![image](https://user-images.githubusercontent.com/1945230/34815109-d1a2b84e-f6b8-11e7-9c45-1621cb41db68.png)
So test passed

**Closed by Uafinder** 2018-01-11 08:19 UTC
Labels: Ready to Test - Dev, bug, enhancement
