### ISSUE TITLE
Add option to badges to allow or not nomination feature

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6855] opened 2019-03-06 09:03 UTC
We need this to Vaya to allow or not badge for nomination. Probably just a boolean switch inside badge options which will enable this feature for some current badge. Should be disabled by default.
https://github.com/Kademi/client-vaya-vayability/issues/386

Also need to select
- who can make nominations
- who can be a nominee

**Comment by bradmac** [comment] 2019-03-08 22:47
Closing as duplicate of https://github.com/Kademi/kademi-dev/issues/6598

**Closed by bradmac** 2019-03-08 22:47 UTC
Labels: High priority, enhancement
