### ISSUE TITLE
From field after save loses information

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2426] opened 2016-09-23 12:35 UTC
- Add a value i.e. "Patrick Hone" <patrick@kademi.co> to an email node using the JB.
- Then click save

![image](https://cloud.githubusercontent.com/assets/2201340/18785748/621aced6-81dd-11e6-824f-ad4d3583a8a3.png)

Then refresh your browser and note the value in the field updates:
![image](https://cloud.githubusercontent.com/assets/2201340/18785831/f596e2c6-81dd-11e6-90d2-6ef3808c9ac3.png)

If you then edit another property and click save, it saves the property value as "Patrick Hone"  causing the email to fail.

Make sure 'From' field keeps it's full syntax.

**Comment by bradmac** [comment] 2016-09-25 21:42
Looks like the value needs to be encoded in the template.

**Comment by paddyow** [comment] 2016-09-26 09:58
also applies to the edit email page.
![image](https://cloud.githubusercontent.com/assets/2201340/18830316/8a4401be-8423-11e6-8527-6da9be52d21c.png)

**Comment by tuzzmaniandevil** [comment] 2016-09-26 23:36
Can't reproduce locally:

![screenshot from 2016-09-27 12-29-19](https://cloud.githubusercontent.com/assets/3378330/18855364/93956876-84ae-11e6-9a5d-482aab87662a.png)

Testing on US, after re-saving the From email it seems to be ok now.

Had a look at commit history and looks like Duc already fixed this issue, The server just needed updating:
https://github.com/Kademi/kademi-dev/issues/2341

@paddyow Please re-check

**Comment by bradmac** [comment] 2016-09-26 23:38
Closing as duplicate - https://github.com/Kademi/kademi-dev/issues/2426#issuecomment-249728191

**Comment by tuzzmaniandevil** [comment] 2016-09-27 23:24
Managed to reproduce the error, It accors when moving a node. When the json saves it breaks the email address.
@ducdhm Please have a look

**Comment by paddyow** [comment] 2016-09-28 15:07
@ducdhm can you get this sorted for me mate.  got a campaign going out and if the subject line changes all the remaining emails break.

**Comment by ducdhm** [comment] 2016-09-28 15:26
@paddyow: Ok sure. In next time, if issue is urgent, please add label `High Priority` for it. I'll complete in current day

**Comment by bradmac** [comment] 2016-09-28 20:47
@ducdhm please continue to work on the Coke project. That has top priority.

**Comment by hoanglinhlan** [comment] 2016-10-05 07:38
passed

**Closed by hoanglinhlan** 2016-10-05 07:38 UTC
Labels: bug, Ready to Test - Dev
