### ISSUE TITLE
Make KChat awesome

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4594] opened 2017-12-11 01:11 UTC

**Comment by Uafinder** [comment] 2017-12-19 08:28
ok, I'm testing here:
frontend: http://vlad09test_vladtest09.kademi-ci.co/
admin: http://vladtest09.admin.kademi-ci.co/
I've create a fresh account, create an admin, create a user and basic group, create a website, install there KChat via marketplace and login to this website with simple user in other browser. So.

First critical:
[ KChat ] :: WS Connection Closed, Re-attempt soon...
![image](https://user-images.githubusercontent.com/1945230/34147063-109de71a-e4a5-11e7-870f-2c6c4d62dffc.png)
![image](https://user-images.githubusercontent.com/1945230/34147234-a62dc444-e4a5-11e7-823e-6a628428cb55.png)

Second critical:
Doublin' typing field, while you are on site some time 
![image](https://user-images.githubusercontent.com/1945230/34147323-fc12cd8c-e4a5-11e7-8ef1-7c5a52576bd0.png)

No image uploading possible:
Drag & drop doesn't work, no upload button

It can't be tested further, need to fix first issue...

And if there is any mention about http and https please note me...

**Comment by tuzzmaniandevil** [comment] 2017-12-21 03:51
All fixed

**Comment by Uafinder** [comment] 2017-12-26 08:10
Firefox still shows error with connection timed out
![image](https://user-images.githubusercontent.com/1945230/34351298-779a9830-ea24-11e7-9bce-8def5898827b.png)
Chrome is ok
Edge also shows error
![image](https://user-images.githubusercontent.com/1945230/34351335-aaf650f2-ea24-11e7-8d8d-fc44f3fd6645.png)

It's probably due the https thing.

**Comment by bradmac** [comment] 2017-12-26 21:57
FF works ok for me, but I'm in the same network as the CI server so that might help.

I think its ok to just test with Chrome on CI, and we'll check other browsers once deployed to prod with correct https certs

**Comment by bradmac** [comment] 2017-12-26 21:59
> and messages doublin' still there:

I cant reproduce. Can you check if still active?

**Comment by Uafinder** [comment] 2017-12-27 12:40
![image](https://user-images.githubusercontent.com/1945230/34381553-f0c34d04-eb11-11e7-8771-12e4a340ef9b.png)
https://vladtest12.admin.kademi-ci.co/websites/vlad12chat/version1/#panel_details-tab

1. Open admin: https://vladtest12.admin.kademi-ci.co/
2. Open in incognito http://vlad12chat-vladtest12.kademi-ci.co/
3. Push some comment from the user side
4. Click on pop-up from admin.
5. Push some answer via admin
6. Push some reply via user side
7. click on pop-up in admin
8. note that admin message is doubling

**Comment by gonzalon** [comment] 2018-02-23 03:28
@Uafinder I did what you explain but I can't reproduce it

**Comment by ducdhm** [comment] 2018-02-23 17:27
@Uafinder @gonzalon I have done an issue related to KChat and I refactored almost styles and code of KChat so I think this issue is already fixed!

**Comment by Uafinder** [comment] 2018-03-02 13:20
1. Visual bug
![image](https://user-images.githubusercontent.com/1945230/36900164-d55d9816-1e2a-11e8-8c2e-ee8e43157366.png)
http://version1.vlad83bchat-vladtest38b.kademi-ci.co/page1.html

2. No kChat button on admin
![image](https://user-images.githubusercontent.com/1945230/36900410-dd25a5d8-1e2b-11e8-93c3-afec3cb3f3a1.png)

3. Click Send does nothing
![image](https://user-images.githubusercontent.com/1945230/36900680-f716d402-1e2c-11e8-90f0-aa6fd23e3dbd.png)

Something are broken, definitely

**Comment by bradmac** [comment] 2018-03-04 19:33
@tuzzmaniandevil please look into issue 2 above

@ducdhm please look into the layout issues 1 and 3. And can you please let me know if this is because the app is using non-standard classes, or if there is a problem in the theme?

**Comment by tuzzmaniandevil** [comment] 2018-03-04 21:53
The JCS cache was corrupt so the lib wasn't being loaded properly. Fixed now

**Comment by tuzzmaniandevil** [comment] 2018-03-04 21:55
Issue 1 and 3 were also related to the JCS cache I think. @ducdhm Just double check to confirm

**Comment by ducdhm** [comment] 2018-03-05 06:47
As I checked, it's working normally.

**Comment by Uafinder** [comment] 2018-03-05 14:33
Yeah, those three last bugs is ok at the moment:
@gonzalon about those which write before
![image](https://user-images.githubusercontent.com/1945230/36979726-03cc7a88-2091-11e8-81eb-d8e10596940a.png)
It's still active
1. Open admin: https://vladtest38d.admin.kademi-ci.co
2. Open in other browser http://vladtest38daucstore-vladtest38d.kademi-ci.co/dashboard
3. Push some comment from user side
4. Click on pop-up from admin side.
5. Push some answer via admin side
6. Push some reply via user side
7. click on pop-up in admin
8. click on back button 
9. click on username again to resume chat with user
10. note that admin message is doubling

**Comment by Uafinder** [comment] 2018-03-13 11:15
Fresh account
App installed via site market place
1. button for kchat from the admin side is absent
https://vladtest40f.admin.kademi-ci.co
![image](https://user-images.githubusercontent.com/1945230/37338568-8136bf3a-26c0-11e8-9007-a2671d5ba8f5.png)

Something broken again

**Comment by bradmac** [comment] 2018-03-13 23:13
Looks ok with a fresh account:

![image](https://user-images.githubusercontent.com/826458/37374693-295127a8-2781-11e8-831c-129e13adfcec.png)

**Comment by Uafinder** [comment] 2018-03-14 08:49
Yeah, looks fine now...

> @gonzalon about those which write before
this bug is ok also

**Comment by Uafinder** [comment] 2018-03-14 09:11
OK, some other suggestions:
When user login it doesn't show instantly in admin console
1. Open admin console https://vladtest41.admin.kademi-ci.co/
2. Open other browser http://vladtest41jour-vladtest41.kademi-ci.co/
3. open kchat panel in admin, note one anonymous appears
4. go to other browser and sign in
5. go back to admin and note that anonymous doesn't change to username
![image](https://user-images.githubusercontent.com/1945230/37392304-6da5f6b4-2776-11e8-8d87-a0c58cc4c525.png)
![image](https://user-images.githubusercontent.com/1945230/37392322-78ae353a-2776-11e8-8e71-5f40177f36ee.png)

The second one is a question:
When you chatting with some user, when he log out and someone resume chatting from that computer, it will keep complete chat history no matter of user logged in.
-Open admin:  https://vladtest41.admin.kademi-ci.co/
-Open in other browser http://vladtest41jour-vladtest41.kademi-ci.co/
-Push some comment from user side
-Click on pop-up from admin side.
-Push some answer via admin side
-logout from user side and refresh page
-open chat again and you will see entire chat history
not sure if it's correct

Urgent bug:
When you chatting with two users in admin, their chat layouts are laying one into another... e.g. second chat will cover first chat
![image](https://user-images.githubusercontent.com/1945230/37392905-3bed3a4a-2778-11e8-9bf4-244dcb5ca8d9.png)
![image](https://user-images.githubusercontent.com/1945230/37392937-553389e6-2778-11e8-9e4b-28a0e27ef9ef.png)

https://vladtest41.admin.kademi-ci.co/

**Comment by tuzzmaniandevil** [comment] 2018-03-15 01:49
Fixed in KChat 1.0.4 and kchat-lib 1.0.4

**Comment by Uafinder** [comment] 2018-03-15 08:28
1. Doubling Kchat notification messages
When user post one message there are two notifications appear
![image](https://user-images.githubusercontent.com/1945230/37450816-29fa4c5e-2838-11e8-9955-7272cc3afdf4.png)
https://vladtest41b.admin.kademi-ci.co

2. When user post two messages in short period sound error appears
![image](https://user-images.githubusercontent.com/1945230/37451451-33a18428-283a-11e8-8193-3ca2b1692469.png)

3. this is still active
When user login it doesn't show instantly in admin console
-Open admin console 
-Open other browser
-open kchat panel in admin, note one anonymous appears
-go to other browser and sign in
-go back to admin and note that anonymous doesn't change to username
![image](https://user-images.githubusercontent.com/1945230/37392304-6da5f6b4-2776-11e8-8d87-a0c58cc4c525.png)
![image](https://user-images.githubusercontent.com/1945230/37392322-78ae353a-2776-11e8-8e71-5f40177f36ee.png)

https://vladtest41b.admin.kademi-ci.co

**Comment by bradmac** [comment] 2018-03-15 08:39
> this is still active
When user login it doesn't show instantly in admin console
-Open admin console
-Open other browser
-open kchat panel in admin, note one anonymous appears
-go to other browser and sign in
-go back to admin and note that anonymous doesn't change to username

This is not a required feature. Please move to a low priority issue, suggest P3

**Comment by bradmac** [comment] 2018-03-15 08:40
> When user post two messages in short period sound error appears

If this is not preventing the app from being used correctly please move to a lower priority issue

**Comment by bradmac** [comment] 2018-03-15 08:41
> Doubling Kchat notification messages
When user post one message there are two notifications appear

We can move that to a P2 issue

**Comment by Uafinder** [comment] 2018-03-15 09:20
https://github.com/Kademi/kademi-dev/issues/5126
https://github.com/Kademi/kademi-dev/issues/5127
https://github.com/Kademi/kademi-dev/issues/5128
All moved away
This one could be closed, will keep an eye on it

**Closed by Uafinder** 2018-03-15 09:20 UTC
Labels: High priority, bug
