### ISSUE TITLE
Upgrade manage orgs page to be like manage users page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3140] opened 2017-04-25 23:28 UTC
- allow faceted search
- by org type

Please do this as a **new** resource and template, so the current page continues to work as it is. Once fully tested we'll switch over to the new one

**Comment by gonzalon** [comment] 2017-07-19 03:00
this is ready for test, the url to access it is /organisations-es/

**Comment by bradmac** [comment] 2017-07-23 22:17
@AlaaKhalaf94 note that you need to enter the address for the new page manually, its not linked to the menu yet.

 /organisations-es/

**Comment by AlaaKhalaf94** [comment] 2017-07-24 06:35
@gonzalon filter by org type is doing well with me
But what about points range ?

**Comment by gonzalon** [comment] 2017-08-21 01:16
@bradmac we said we werent going to do the points range.
should I do it now or open another issue for it?

**Comment by bradmac** [comment] 2017-08-21 04:00
Removed that requirement. Will address it in a later milestone

**Comment by Uafinder** [comment] 2017-09-21 14:33
Bugs!
![image](https://user-images.githubusercontent.com/1945230/30701423-e73c6ccc-9ef2-11e7-9b70-f389c86883c4.png)

**Comment by Uafinder** [comment] 2017-09-21 14:40
Also sorting incorrect...
![image](https://user-images.githubusercontent.com/1945230/30701796-dfea587a-9ef3-11e7-8888-c633624e4ef9.png)

**Comment by gonzalon** [comment] 2017-09-26 22:06
![image](https://user-images.githubusercontent.com/2773216/30886526-ceb68c2a-a373-11e7-8c05-7fb16b333de1.png)

@bradmac should we merge these into the tool button? 

- Assign to org type
- Merge selected..
- Move to parent 

Remove can be another button and delete sorting ones

**Comment by gonzalon** [comment] 2017-09-27 02:05
Added the default ordering for orgId desc

**Comment by Uafinder** [comment] 2017-10-04 14:01
http://vlad-test9.admin.kademi-ci.co/organisations-es
adminqa@mailinator.com

1. When push remove button and forget to put checkboxes.
![image](https://user-images.githubusercontent.com/1945230/31179626-1d9f2750-a925-11e7-991d-64930750d005.png)

2. Default sorting is working but it is in incorrect direction e.g. Z-A, and it's case sensitive e.g. Upper characters and lower characters sorting different.
![image](https://user-images.githubusercontent.com/1945230/31179735-6f56ba68-a925-11e7-8223-dd49b10501b2.png)

**Comment by gonzalon** [comment] 2017-10-05 00:36
@Uafinder I cant reproduce the multiple messages for the delete. Can you please tell me how to reproduce this? Thanks

**Comment by gonzalon** [comment] 2017-10-05 01:17
@anhnt could you please make the change to avoid the multiple messages in the delete validation?

**Comment by Uafinder** [comment] 2017-10-10 11:25
All looks pretty, page ready to be implemented

**Comment by gonzalon** [comment] 2017-10-10 20:58
Need to change the menu

**Comment by gonzalon** [comment] 2017-10-10 21:11
Also need to fix this: https://github.com/Kademi/kademi-dev/issues/4134#event-1286923879

**Comment by Uafinder** [comment] 2017-10-11 12:17
4134 shouldn't be fixed for new page... it's related to incorrect sorting order e.g. Upper case and lower case...

A few more:
1. Sorting by Org type cause page to be empty
![image](https://user-images.githubusercontent.com/1945230/31439928-b70c11d4-ae96-11e7-9a4b-b00dbdc8fe39.png)
result
![image](https://user-images.githubusercontent.com/1945230/31439958-d51ab37e-ae96-11e7-9017-d1d3bb891886.png)

2. Incorrect sorting when you manually choose sorting by name or orgID... it puts Upper case first to lower case again :(
![image](https://user-images.githubusercontent.com/1945230/31440024-1c4b5af0-ae97-11e7-8c14-1687b84e6e9b.png)
![image](https://user-images.githubusercontent.com/1945230/31440033-278f3580-ae97-11e7-958e-ab3b0c8d3ca1.png)

http://vlad-test12.admin.kademi-ci.co/organisations-es/

**Comment by gonzalon** [comment] 2017-10-12 02:48
@Uafinder 
1. was caused because a change in the index, as this page use elasticsearch a re index was needed
2. fixed other two

**Comment by Uafinder** [comment] 2017-10-12 12:46
I checked it a few mins ago:
1. The org himself shouldn't appears in the list
http://vlad-test13.admin.kademi-ci.co/organisations-es
![image](https://user-images.githubusercontent.com/1945230/31496451-07dc3648-af64-11e7-9a47-5bcca3d2266a.png)

2. Sorting by orgType incorrect
http://vlad-test13.admin.kademi-ci.co/organisations-es
![image](https://user-images.githubusercontent.com/1945230/31496537-781aba9c-af64-11e7-88b1-7b4a5d19777c.png)

**Comment by gonzalon** [comment] 2017-10-12 23:58
1. Fixed
2. Just made the re index and the sorting by its fine. Going to take a look if we fire the re index, might be a issue there

**Comment by gonzalon** [comment] 2017-10-13 03:55
@Uafinder if everything is ok please assign it back to me so I can change the menu and I'll close it after that :+1:

**Comment by Uafinder** [comment] 2017-10-13 07:05
Great, it works
Probably would be great to check again after menu change. So please re-assign it to me when you complete changes.

**Comment by Uafinder** [comment] 2017-10-16 10:36
Minor issues:
1. When path contains more then one chain e.g. /org1/org2
![image](https://user-images.githubusercontent.com/1945230/31607843-b6640d98-b276-11e7-8234-9e7cefd492b2.png)

2. Address descending sorting in not working.
![image](https://user-images.githubusercontent.com/1945230/31607911-f5bdd960-b276-11e7-9b53-946c552ec155.png)

http://vlad-test17.admin.kademi-ci.co/organisations

**Comment by gonzalon** [comment] 2017-10-18 03:21
Took it off failing for carters https://carters.admin.kademi.com.au/organisations-es/
Probably is the pagination

**Comment by bradmac** [comment] 2017-10-18 03:23
Please re-test locally with a large database of orgs, eg 10k

Also, need to make sure that soft-deleted organisations are not displayed

**Comment by gonzalon** [comment] 2017-10-18 23:10
@Uafinder You can use this file to import orgs if you change the number in L1 change the names for the orgs so you can import it multiple times 
[orgs-import.xls.zip](https://github.com/Kademi/kademi-dev/files/1396585/orgs-import.xls.zip)

**Comment by Uafinder** [comment] 2017-10-20 09:08
OrgType and OrgName search incorrect.
![image](https://user-images.githubusercontent.com/1945230/31812026-55610d5e-b58a-11e7-8b31-83f2800b911d.png)
http://vlad-test21.admin.kademi-ci.co/organisations-es

**Comment by gonzalon** [comment] 2017-10-24 02:03
@Uafinder 
1) Sorry I'm not really sure if I get what you mean with: "OrgType and OrgName and Phone search incorrect." as the screen points to different things?
But the search its working for me, tried orgType and orgName. We are not supporting the phone atm.

2) Fixed

3) We only support to show 10 pages, but if you click in the last arrow the pagination works.
Added the option to change the page size, so it's more practical for larger amount of records:
![image](https://user-images.githubusercontent.com/2773216/31921484-186a8a16-b8cc-11e7-9577-c32512444dab.png)

**Comment by bradmac** [comment] 2017-10-24 07:44
![image](https://user-images.githubusercontent.com/826458/31930305-c842779e-b8fb-11e7-8a59-888271d7f2fc.png)

**Comment by bradmac** [comment] 2017-10-24 07:46
Also, sorting by phone number is incorrect. Blanks should be together:

![image](https://user-images.githubusercontent.com/826458/31930484-5577828a-b8fc-11e7-8cad-b26cdb4548e4.png)

**Comment by gonzalon** [comment] 2017-10-26 03:31
Added:
![image](https://user-images.githubusercontent.com/2773216/32033784-195527ba-ba6b-11e7-878d-b7088f70c884.png)

Sorting by phone its fixed

**Comment by Uafinder** [comment] 2017-11-01 07:58
Descending sorting incorrect looks like on all fields.
For example when you sort by "Type" asc - filled up should be on the top, when desc - should be on the bottom.
![image](https://user-images.githubusercontent.com/1945230/32265305-244672f8-beeb-11e7-8715-059cac5e674d.png)

And for example Address desc - numbers will be always on top of the list.
![image](https://user-images.githubusercontent.com/1945230/32265311-2cf31910-beeb-11e7-9bd7-10c6cf2a9787.png)
![image](https://user-images.githubusercontent.com/1945230/32265330-37e371e4-beeb-11e7-8d11-f34ebfb6c04e.png)

**Comment by gonzalon** [comment] 2017-11-08 23:02
@Uafinder ok I found the issue why we were having so much troubles with the sorting! now it should be fine for good!

Just note that the blanks are never going to be on top, that's how the sorting of ES works, and actually you can see the same behaviour in the users page.

**Comment by Uafinder** [comment] 2017-11-09 12:53
Sorting great!

**Closed by Uafinder** 2017-11-09 12:53 UTC
Labels: bug, Ready to Test - Dev
