### ISSUE TITLE
KCRM: Org dropdown duplicate values such times which user had memberships

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1549] opened 2016-03-24 14:42 UTC
![image](https://cloud.githubusercontent.com/assets/1945230/14020327/537f75f4-f1df-11e5-9e20-e3a37f662bf5.png)

**Comment by anhnt** [comment] 2016-03-24 15:45
duplicate of https://github.com/Kademi/kademi-dev/issues/1533

**Closed by anhnt** 2016-03-24 15:45 UTC
Labels: bug
